### PR TITLE
Support pt-BR

### PR DESCRIPTION
**Pull request by hendrilmendes**

### CODE REVIEW

**Comment by mediaexplorer74** [comment]
> _ No description provided. _

Hi Hendril Mendes,
thank you for this PR. I'm only "c# hobbyist", more 100 projectsis only "damaged forks"  , no less, no more... UnigramMobile is only strange idea to improve obsolete Unigram project (in modern times, it has no support of retro-phones such as Nokia Lumia). So, this repo is very "early bird". ANd I have no community... I single-developer. Your PR is first in Github, to me ) Idk what to do... Please be patient ) 
I revised a little your code... I noticed some Brazilian words at "en" folder. Is it right or wrong?

**Review by mediaexplorer74 — APPROVED** [review]

**Review by mediaexplorer74 — CHANGES_REQUESTED** [review]
I don't like non-native modification of "en" folder. English is not my native languege... however, it's some kind of "Esperanto" =)

**Review by mediaexplorer74 — APPROVED** [review]
I decided to approve your PR... It's interesting to me. Thank you for new "Pair programming" experiense :) Have a nice day!

**Comment by hendrilmendes** [comment]
Hi, I made a mistake when pushing, I apologize for the mistake, I will push
the correction

Em dom., 25 de fev. de 2024 às 12:21, Media Explorer <
***@***.***> escreveu:

**Review by mediaexplorer74 — COMMENTED** [review]
Cool. You're welcome!

**Review by mediaexplorer74 — APPROVED** [review]

**Review by mediaexplorer74 — APPROVED** [review]

**Pull request merged**
